# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: cyril-linux.local:5050/cyril/imperx_python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - python -m venv venv
  - source venv/bin/activate

test:
  script:
    - pip install tox
    - tox

run:
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
    TWINE_CERT: /etc/ssl/certs/ca-certificates.crt
    TWINE_REPOSITORY_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  script:
    - pip install wheel twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  artifacts:
    paths:
      - dist/*.whl
